In [39]:
import pandas as pd 
import os 
df = pd.read_parquet(r"D:\fraud_detection_using_ML\data\raw\ieee_fraud_detection.parquet", engine= "pyarrow")

In [40]:
df.shape

(590528, 202)

In [41]:
df.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V312,V313,V314,V315,V316,V317,V318,V319,V320,V321
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,0.0,0.0,0.0,0.0,0.0,117.0,0.0,0.0,0.0,0.0
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,135.0,0.0,0.0,0.0,50.0,1404.0,790.0,0.0,0.0,0.0
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
df.sample(10)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V312,V313,V314,V315,V316,V317,V318,V319,V320,V321
134791,3121792,0,2686772,32.355999,C,9026,545.0,185.0,visa,137.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
144651,3131652,0,2989156,57.950001,W,12559,555.0,150.0,visa,226.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
302556,3289557,0,7490910,117.000000,W,2845,543.0,150.0,mastercard,117.0,...,433.850006,0.0,0.0,0.0,0.0,381.799988,0.0,0.0,57.950001,0.0
381823,3368824,0,9566701,662.099976,W,10616,583.0,150.0,visa,226.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
128214,3115215,0,2559307,20.000000,W,16115,431.0,150.0,visa,166.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
584411,3571423,0,15625227,300.000000,R,10024,321.0,150.0,visa,144.0,...,0.000000,0.0,0.0,0.0,300.0,300.000000,300.0,0.0,0.000000,0.0
532025,3519037,0,14002496,189.949997,W,17188,321.0,150.0,visa,226.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
546644,3533656,0,14423941,317.459991,W,15066,170.0,150.0,mastercard,102.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
322865,3309866,0,8012574,44.500000,W,3094,276.0,150.0,visa,226.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
521031,3508037,0,13695844,325.000000,W,3518,514.0,150.0,mastercard,195.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0

In [43]:
fraud_df = df[df["isFraud"] == 1]

fraud_df

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V312,V313,V314,V315,V316,V317,V318,V319,V320,V321
203,2987203,1,89760,445.000000,W,18268,583.0,150.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0
240,2987240,1,90193,37.098000,C,13413,103.0,185.0,visa,137.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0
243,2987243,1,90246,37.098000,C,13413,103.0,185.0,visa,137.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0
245,2987245,1,90295,37.098000,C,13413,103.0,185.0,visa,137.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0
288,2987288,1,90986,155.520996,C,16578,545.0,185.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590349,3577361,1,15807368,1224.000000,W,3278,453.0,150.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0
590352,3577364,1,15807516,69.963997,C,5812,408.0,185.0,mastercard,224.0,...,0.0,0.0,0.0,0.0,0.0,48.0774,0.0,0.0,0.0,0.0
590356,3577368,1,15807677,100.000000,H,6758,399.0,150.0,american express,146.0,...,0.0,NaN,NaN,NaN,0.0,0.0000,0.0,0.0,0.0,0.0
590360,3577372,1,15807758,117.000000,W,14037,111.0,150.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0
590514,3577526,1,15810876,250.000000,R,1214,174.0,150.0,visa,226.0,...,0.0,NaN,NaN,NaN,0.0,0.0000,0.0,0.0,0.0,0.0

In [44]:
df["isFraud"].value_counts()

isFraud
0    569865
1     20663
Name: count, dtype: int64

In [45]:
# Set the TransactionID to index
df.set_index('TransactionID', inplace=True)

In [46]:
df.head()

,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,V312,V313,V314,V315,V316,V317,V318,V319,V320,V321
TransactionID,,,,,,,,,,,,,,,,,,,,,
2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,credit,...,0.0,0.0,0.0,0.0,0.0,117.0,0.0,0.0,0.0,0.0
2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,...,135.0,0.0,0.0,0.0,50.0,1404.0,790.0,0.0,0.0,0.0
2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 590528 entries, 2987000 to 3577539
Columns: 201 entries, isFraud to V321
dtypes: float32(193), int32(3), object(5)
memory usage: 466.3+ MB

In [50]:
df.dtypes

isFraud             int32
TransactionDT       int32
TransactionAmt    float32
ProductCD          object
card1               int32
                   ...
V317              float32
V318              float32
V319              float32
V320              float32
V321              float32
Length: 201, dtype: object

In [51]:
df.dtypes.value_counts()

float32    193
object       5
int32        3
Name: count, dtype: int64

### Data Cleaning and Preprocessing

In [57]:
def check_missing(df, dtype='object'):
    # Total number of rows
    total_rows = df.shape[0]

    # Check missing values and their percentage for specified dtype
    missing_ = df.select_dtypes(include=dtype).isnull().sum()
    missing_percent = (missing_ / total_rows) * 100

    # Combine into a DataFrame for better readability
    missing_summary = pd.DataFrame({
        'Missing Values': missing_,
        'Missing Percentage (%)': missing_percent.round(2)
    })

    # Filter out columns without missing values
    missing_summary = missing_summary[missing_summary['Missing Values'] > 0]

    # Sort by missing percentage
    return missing_summary.sort_values(by='Missing Percentage (%)', ascending=False)

In [58]:
# For numeric types
check_missing(df, dtype=['float32', 'int32'])

      Missing Values  Missing Percentage (%)
V52           168957                   28.61
V51           168957                   28.61
V37           168957                   28.61
V38           168957                   28.61
V39           168957                   28.61
...              ...                     ...
V317              11                    0.00
V318              11                    0.00
V319              11                    0.00
V320              11                    0.00
V321              11                    0.00

[178 rows x 2 columns]